const express = require('express');
const app = express();
bodyParser = require('body-parser');

app.use(bodyParser.json());

app.use(express.urlencoded({ extended: false }));

let artistModel = require(__dirname + "/model/artistModel.js");
let artGalleryModel = require(__dirname + "/model/artGalleryModel.js");
let transactionModel = require(__dirname + "/model/transactionModel.js");
let artworkModel = require(__dirname + "/model/artworkModel.js");



// Artist routes
app.post('/artistSearch', (req, res) => {

    let artistSearch = req.body.artist;

    artistModel.findArtistByName(artistSearch)
    .then(artists=>{res.send(artists)})
    .catch(err=>{res.send(err)})

});

// Developer: Pratt
// Get Artist information by ID
app.get('/getArtistByID/:artistId', (req, res) => {

    const artistId = req.params.artistId;

    artistModel.getArtistByID(artistId)
    .then(artist=>{res.send(artist)})
    .catch(err=>{res.send(err)})
})

// Developer: Pratt
// Endpoint to get the Top 30 artists of all time based on the income generated by their artworks through Knack.
app.get('/popularArtists', (req, res) => {

    artistModel.fetchPopularArtists()
    .then(popularArtists=>{res.send(popularArtists)})
    .catch(err=>{res.send(err)})
})

// Developer: John
// Endpoint to fetch all the artists in the Database
app.get('/getAllArtists', (req, res) => {

    artistModel.getAllArtists()
    .then(artists=>{res.send(artists)})
    .catch(err=>{res.send(err)})
})

//Developer: Carol
// EndPoint to fetch all the artwork by artist name
app.get('/artworkByArtist/:artistName', (req, res) => {

    let artistName = req.params.artistName;

    artworkModel.findArtworkByArtistName(artistName)
    .then(artwork=>{res.send(artwork)})
    .catch(err=>{res.send(err)})

});

//Developer: Carol
// EndPoint to fetch all the artwork 
// by keywords: Artwork Description, Artist (Creator) name, Seller (Gallery or Artist) name, Period, Medium, 
app.get('/artworkByKeyword/:keyword?', (req, res) => {

    let keyword = (req.params.keyword == undefined ? "" : req.params.keyword);

    artworkModel.findArtworkByKeyword(keyword)
    .then(artwork=>{res.send(artwork)})
    .catch(err=>{res.send(err)})

});




// Art Gallery routes
// Developer: Pratt
// Get Art Gallery information by ID
app.get('/getArtGalleryByID/:artGalleryId', (req, res) => {
    const artGalleryId = req.params.artGalleryId

    artGalleryModel.getArtGalleryByID(artGalleryId)
    .then(artGallery=>{res.send(artGallery)})
    .catch(err=>{res.send(err)})
})

// Developer: John
// Get Art Galleries
app.get('/getArtGalleries', (req, res) => {

    artGalleryModel.getArtGalleries()
    .then(artGallerys=>{res.send(artGallerys)})
    .catch(err=>{res.send(err)})
})


//Transaction routes
// Developer: Pratt
// Handle the rent or purchase of an Artwork
app.post('/placeOrder', (req, res) => {
    const purchaseInfo = {
        idCustomer: req.body.idCustomer,
        idArtwork: req.body.idArtwork,
        orderType: req.body.orderType,
        idPaymentMethod: req.body.idPaymentMethod,
        rentalStartDate: req.body.rentalStartDate,
        rentalEndDate: req.body.rentalEndDate
    }

    transactionModel.placeOrder(purchaseInfo)
    .then(result=>{res.send(result)})
    .catch(err=>{res.send(err)})
});

app.set('port', process.env.PORT || 8080);

const server = app.listen(app.get('port'), ()=>{
    console.log("Listening on port: "+ app.get('port'));
});
