const express = require("express");
const router = express.Router();

let artistModel = require("../model/artistModel.js");

// Developer: Pratt
// Get Artist information by ID
router.get('/getArtistByID/:artistId', (req, res) => {

    const artistId = req.params.artistId;

    artistModel.getArtistByID(artistId)
    .then(artist=>{res.send(artist)})
    .catch(err=>{res.send(err)})
})

// Developer: Pratt
// Endpoint to get the Top 30 artists of all time based on the income generated by their artworks through Knack.
router.get('/popularArtists', (req, res) => {

    artistModel.fetchPopularArtists()
    .then(popularArtists=>{res.send(popularArtists)})
    .catch(err=>{res.send(err)})
})

// Developer: John
// Endpoint to fetch all the artists in the Database
router.get('/getAllArtists', (req, res) => {

    artistModel.getAllArtists()
    .then(artists=>{res.send(artists)})
    .catch(err=>{res.send(err)})
})

// Developer: Carol
// endpoint to search Artists by any keyword
router.post('/artistSearch', (req, res) => {

    let artistSearch = req.body.artist;

    artistModel.findArtistByName(artistSearch)
    .then(artists=>{res.send(artists)})
    .catch(err=>{res.send(err)})

});

exports.artistRouter = router;