const express = require("express");
const router = express.Router();

let artistController = require("../controllers/artistController.js");


// Developer: Pratt
// Get Artist information by ID
router.get('/artists/:artistId', artistController.getArtistByID)

// Developer: Pratt
// Endpoint to get the Top 30 artists of all time based on the income generated by their artworks through Knack.
router.get('/popularArtists', artistController.fetchPopularArtists)

// Developer: John
// Endpoint to fetch all the artists in the Database
router.get('/artists', artistController.getAllArtists)

// Developer: Carol
// endpoint to search Artists by any Name
router.get('/artists/search/:artistName', artistController.getArtistByName);

exports.artistRouter = router;